server:
  port: 8081
debug: true
logging:
  level:
    com:
      aichong:
        mapper: debug
##数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://101.132.115.227:3306/aichong?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  security:
    basic:
      path: /swagger-ui.html
      enabled: true
